controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /auth
    methods: ['POST']
    
patient_dossiers:
    path: /api/patients/{id}/dossiers
    controller: App\Controller\DossierController::getPatientDossiers
